### ISSUE TITLE
No such file or directory: '.settings/com.appcelerator.titanium.mobile.prefs'

### ISSUE THREAD

**Issue by shaynekang** [akahigeg/jasmine-titanium#1]
And I don't have the file com.appcelerator.titanium.mobile.prefs

How can I fix this issue?

**Comment by shaynekang** [comment]
I found that!

 I didn't have the com.appcelerator.titanium.mobile.prefs because I created the project in Titanium Developer(not Titanium Studio)

**Comment by akahigeg** [comment]
thank you for catching this!

**Comment by shaynekang** [comment]
You're welcome. :D
